[package]
name = "finchers-juniper"
version = "0.0.1"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

build = "build.rs"

[dependencies]
finchers = { git = "https://github.com/finchers-rs/finchers.git", branch = "master" }
#finchers = "0.12.0-alpha.3"

bytes = "0.4.9"
failure = { version = "0.1.2", features = ["derive"] }
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", branch = "master", features = ["tokio-compat"] }
http = "0.1.10"
juniper = { git = "https://github.com/graphql-rust/juniper.git", branch = "master" }
percent-encoding = "1.0.1"
pin-utils = "0.1.0-alpha.2"
serde = { version = "1.0.75", features = ["derive"] }
serde_json = "1.0.26"
serde_qs = "0.4.1"
tokio = "0.1.8"
tokio-threadpool = "0.1.6"

[build-dependencies]
version_check = "0.1.4"
